use_frameworks!

platform :ios, '8.0'

target 'LLWebView_Example' do
  pod 'LLWebView', :path => '../'

  pod 'Masonry', '~> 1.1.0'
  pod 'Reachability', '~> 3.2'

  target 'LLWebView_Tests' do
    inherit! :search_paths

    
  end
end
